### ISSUE TITLE
Pull interval

### ISSUE THREAD

**Issue by Matthijsbr123** [ArekKubacki/Hoymiles-Plant-DTU-Pro#10]
Hello,

Thnx for your great solution. I tried to pull the data in 1 minute, but it don't work. Any Tips or Tricks ?

sensor:
  - platform: hoymiles_dtu
    host: 192.168.X.X
    name: Hoymiles PV
    scan_interval: 00:01:00
    monitored_conditions:
      - 'pv_power'
      - 'today_production'
      - 'total_production'
      - 'alarm_flag'
    monitored_conditions_pv:
      - 'pv_power'

**Comment by ArekKubacki** [comment]
Is the DTU connected via the ETH cable?

**Comment by Matthijsbr123** [comment]
Yes

**Comment by ArekKubacki** [comment]
That's one more question. Are you receiving data and want to increase the ic number every minute or are you not receiving data at all?

**Comment by Matthijsbr123** [comment]
Yes i receive data, seems like every 5 minutes. I searched in the settings to speed up to 1 Minute

**Comment by ArekKubacki** [comment]
Unfortunately they have changed it to HA for a while now. All sessions that are total type are refreshed every 5 minutes.

https://developers.home-assistant.io/docs/core/entity/sensor/

**Comment by Matthijsbr123** [comment]
Better than 15 minutes. Thanks for your support !

**Comment by ArekKubacki** [comment]
In the new version, everything except total and today production will no longer be in the measurement class, so you will be able to refresh more often.
