### ISSUE TITLE
Unique IDs for HomeAssistant

### ISSUE THREAD

**Issue by obstler42** [ArekKubacki/Hoymiles-Plant-DTU-Pro#11]
Is it possible to add Unique IDs to the sensors for customizing in HomeAssistant? Right now no sensor customization is possible:

`This entity ('sensor.hoymiles_pv_pv_power') does not have a unique ID, therefore its settings cannot be managed from the UI. See the [documentation](https://www.home-assistant.io/faq/unique_id) for more detail.`

**Comment by ArekKubacki** [comment]
I am testing the version in which I already have this field completed. Please wait a week or two.

**Comment by R-yenScotch** [comment]
Will solar production be visible in the energy dashboard when unique id's are added?

**Comment by ArekKubacki** [comment]
This functionality is now available. Unique ID has nothing to do with it.

**Comment by R-yenScotch** [comment]
Terribly sorry.. found it! Didn't know where to add solar production in the energy management system.. Rookie mistake..

**Comment by ArekKubacki** [comment]
Thank you very much :)

**Comment by FvanEgmond** [comment]
I'd like to doublecheck if the unique IDs are indeed implemented as this thread suggests. I am using this custom integration now for 11 months, and updated to the latest version (0.6) via HACS when it came out, but my sensors aren't showing any unique_id attributes in Home Assistant.
Should the integration be removed and reinstalled/reconfigurated to do so?
Thanks in advance for any help/pointers/reply!
