### ISSUE TITLE
DTUPro-safter adding the DTU interval it started to hang

### ISSUE THREAD

**Issue by Maximus1022012** [ArekKubacki/Hoymiles-Plant-DTU-Pro#14]
Hello

Previously, I had 4 months of installed version without scan_interval and it worked fine minor distortions as the panels finished production around 20.00. I added the scan_interval parameter and the DTU started crashing. After a week, he completely refused to obey the power LED 1 lights up and after a while the LEDs 2 and 3 blink synchronously no DTUP wifi network no lan connection, reset does not help. Several people have had this problem with no solution.

https://www.elektroda.pl/rtvforum/topic3867694-120.html

Maximus102

**Comment by ArekKubacki** [comment]
Tak jak pisałem kilka razy, DTU nie jest najlepszym produktem. Polecam złożyć OpenDTU. Koszt jest śmiesznie niski. Sam go używam od kilku miesięcy i zapomniałem co to są problemy z DTU.

**Comment by GL640** [comment]
> As I wrote several times, DTU is not the best product. I recommend submitting OpenDTU. The cost is ridiculously low. I've been using it myself for a few months and forgot what DTU problems are.

wy are you stil promoting the dtu pro then with this github softwarea?
"Hoymiles Plant DTU-Pro Sensor

This integration retrieves data from Hoymiles DTU-Pro using Modbus TCP do Home Assistant"
