### ISSUE TITLE
Energy Spike after sunset

### ISSUE THREAD

**Issue by erwinvana** [ArekKubacki/Hoymiles-Plant-DTU-Pro#17]
Hello,
I have a spike after sunset, its not everyday , but its like 5 out of 7 days a week.
Apparently this is know issue with HA.
Form the Link:
[https://community.home-assistant.io/t/energy-dashboard-shows-crazy-and-unrealistic-energy-spike/479252/7](url)

**this can be resolved by:**
_integration developer should implement an “unavailable state” - or by creating a manual template sensor where you refer to the sensors state - but implement a check against zero-values._

i know i can correct this through the developer statistic option, but i don't think that is a long term solution.
Can you please advise in this ?

Screenshot of Issue:
![EnergySpike](https://github.com/ArekKubacki/Hoymiles-Plant-DTU-Pro/assets/55002008/a41f51a4-f156-46aa-9141-2ab9b2c55473)

**Comment by ArekKubacki** [comment]
What variable are you using in Energy dashboard?

**Comment by erwinvana** [comment]
<img width="305" alt="image" src="https://github.com/ArekKubacki/Hoymiles-Plant-DTU-Pro/assets/55002008/9258c751-6857-4227-9185-55f9c01c1410">

**Comment by ArekKubacki** [comment]
That is why such peaks occur. Change to **total** according to the information in the Readme and forget about the problem.
