### ISSUE TITLE
DTU bricks when modbus data used

### ISSUE THREAD

**Issue by GL640** [ArekKubacki/Hoymiles-Plant-DTU-Pro#20]
i dont see any messages about that the dtu pro bricks when you readout data from the modbus-tcp ( ethernet ) after a while
compleet device is useless have to send it in and get a new one.
i am not the only one so with this expirience

**Comment by ArekKubacki** [comment]
I think these are comments for the developer of the library. As I have mentioned many times, DTU is not the best product.

**Comment by FvanEgmond** [comment]
I had this issue too (2 bricked DTU- Pro's) and could prevent this from happening again by letting the update interval to 15 minutes. Since then, it has been running smoothly for over 10 months now.
