### ISSUE TITLE
Wrong value in Energy dashboard

### ISSUE THREAD

**Issue by erwinvana** [ArekKubacki/Hoymiles-Plant-DTU-Pro#23]
Since a couple of days, i have a strange value reported in teh HA Energy Dashboard.
I see 1 nagative spike in he morning (today -2,114.58 kWh), but no values the rest of the day
In the Hoymiles page in HA i can see teh output per panel and that looks fine.
![energydash01](https://github.com/ArekKubacki/Hoymiles-Plant-DTU-Pro/assets/55002008/f18df8cb-9c35-4562-8a7f-cf8f65e5ddf3)
![solarpanels](https://github.com/ArekKubacki/Hoymiles-Plant-DTU-Pro/assets/55002008/b950094f-ecde-4a46-b2bb-0c7f80e35cb8)
![hoymiles](https://github.com/ArekKubacki/Hoymiles-Plant-DTU-Pro/assets/55002008/9a35efee-0822-4c9f-96d0-d1dbb0e37b3f)

**Comment by ArekKubacki** [comment]
Have you restarted HA in the meantime?

**Comment by erwinvana** [comment]
Hello ArekKubacki ,

Ive restarted HA multiple times, didnt solve it…

k.r.,
 Erwin


Verstuurd vanaf mijn iPhone

Op 27 jan 2024 om 10:28 heeft ArekKubacki ***@***.***> het volgende geschreven:

﻿

Have you restarted HA in the meantime?

**Comment by erwinvana** [comment]
I tested with the other vallue "Hoymiles PV today_production"  (which had other known issues in the end of the day) this seems to work. 
![ha_hoymiles](https://github.com/ArekKubacki/Hoymiles-Plant-DTU-Pro/assets/55002008/628604e1-f2bb-4720-9edf-eca7d22b73ab)
