### ISSUE TITLE
"So you have to go to "Toolkit" in APP and then choose "Remote Control" from RS-485 Port Config under DTU Information"

### ISSUE THREAD

**Issue by bynight66** [ArekKubacki/Hoymiles-Plant-DTU-Pro#29]
There is a Port requested... Which is the correct one?

**Comment by ArekKubacki** [comment]
Port 502 id 1

**Comment by bynight66** [comment]
Thanks for your fast Answer. 
But there is neighter port 502 nor ID 1. 
I can choose a Portaddress from 101 till 254.
![Hoymiles_Port](https://github.com/ArekKubacki/Hoymiles-Plant-DTU-Pro/assets/141565360/81ff609c-2042-40e2-82b3-550c1d27c679)

**Comment by ArekKubacki** [comment]
If i remember 101.
