### ISSUE TITLE
błędne odczyty danych pojawiające się losowo.

### ISSUE THREAD

**Issue by rafalbremer** [ArekKubacki/Hoymiles-Plant-DTU-Pro#3]
Cześć,

Na wstępie chciałbym powiedzieć @ArekKubacki , że świetna robota. Zainstalowałem integrację i działa od pierwszego "strzału". Bardzo dziękuję!

Chciałbym także podzielić się pewną obserwacją, która dotyczy błędnych danych pojawiających co pewien czas. Mianowicie raz na jakiś czas (nie ustaliłem żadnego powtarzalnego schematu) pojawia się odczyt bardzo dużej produkcji prądu przez instalację PV w czasie gdy ta instalacja nie produkuje nic, czyli po zmroku. Wszystkie pozostałe odczyty z tego dnia są OK, ale całość produkcji jest zawyżona.

tu przykład:
![image](https://user-images.githubusercontent.com/104586991/187269620-12df63d5-4193-4554-8ddc-ebc474fefdd0.png)
![image](https://user-images.githubusercontent.com/104586991/187269723-b1a0369a-a60c-44d8-9f63-3e877aca76ca.png)

nie umiem niestety ustalić gdzie leży problem. W natywnej aplikacji hoymiles takich odczytów nie mam. 
Co ciekawe na wykresie historii entity PV_todays_production widac pewne anomalie dokladnie w momentach wystapienia błędnych odczytów. W miejscach dzie pojawiają się nagłe spadki np. 21 AUG. 

![image](https://user-images.githubusercontent.com/104586991/187271062-c7aca92a-0d01-494f-bf19-dcfc75c52801.png)

Ciekaw jestem czy ktoś zaobserwował podobne zachowanie u siebie?

English vesion:
First of all I would like to say @ArekKubacki good job!. I've installed integration and it works from "first shot".

I would like to share some observed anomaly that cause incorrect data. Randomly Hoymiles PV today_production shows high production of my PV installation when it is not possible, eg. during night hours. All other data seems to be OK. Anyway total production shows incorrect data. SEE screens attached.

I don't know what cause the issue. Native Hoymiles app shows correct data. Additionally history graph shows these anomalies as well (see drop downs on attached graph). See attached screen above.

I would like to ask if anyone spotted the same issue.

Rafal

Pozdrawiam
Rafał

**Comment by ArekKubacki** [comment]
Dzięki za miłe słowa :) zachęcam do postawienia kawy odpowiednim przyciskiem ;)

Wracając do tematu. Zauważyłem pewną rzecz u siebie i obstawiam, że przyczyną jest to również u Ciebie. Czasami jeden z inwerterów traci polaczenie z DTU ale ono tego nie widzi i sumarycznie daje to mniejszy odczyt. Po ponownym połączeniu jest już ok. Niestety jeśli jest to między godzinami zakładka Energy wariuje. Zabezpieczona przed tym jest zmienna Total dlatego proszę użyj jej do Energy zamiast today. Powinno pomóc. Taki już urok niedopracowanego DTU :). Daj znać czy na Total jest poprawnie.
