### ISSUE TITLE
Problem with DTU Pro configuration

### ISSUE THREAD

**Issue by Mazurekmazi** [ArekKubacki/Hoymiles-Plant-DTU-Pro#30]
Hello.

Problem with DTU Pro configuration, eth connection, configuration as in the manual
  sensor:
    - platform: hoymiles_dtu
      host: 192.168.1.234
      name: Hoymiles PV
      dtu_type: 0
      monitored_conditions:
        - 'pv_power'
        - 'today_production'
        - 'total_production'
        - 'alarm_flag'
      monitored_conditions_pv:
        - 'pv_power'
        - 'today_production'
        - 'total_production'
        - 'pv_voltage'
        - 'pv_current'
        - 'grid_voltage'
        - 'temperature'
        - 'operating_status'
        - 'alarm_code'
        - 'alarm_count'
        - 'link_status'
      panels: 6

Error as below.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hoymiles_dtu/sensor.py", line 69, in setup_platform
    raise Exception('Invalid configuration for Hoymiles DTU platform')
Exception: Invalid configuration for Hoymiles DTU platform

Pozdrawiam

**Comment by ArekKubacki** [comment]
A topic in Polish has been created. In the rest, the standard language is English.

Are you sure IP is eth? Sometimes dtu connects both via wifi and eth. You need to be sure.

Have you followed?:
!!! For 22 Version, if you choose "Export control", it prohibits MODBUS TCP. But "Remote control" still supports it. So you have to go to "Toolkit" in APP and then choose "Remote Control" from RS-485 Port Config under DTU Information. !!!

**Comment by Mazurekmazi** [comment]
I haven't configured the WiFi, so it's probably connected via eth, the IP address is set on the Mikrotik, so the ports are probably entered correctly, and the ones that need to be redirected, I haven't set up export management, and the error is still displayed.

**Comment by Mazurekmazi** [comment]
I fix the problem. Thx
