### ISSUE TITLE
DTU-Port

### ISSUE THREAD

**Issue by XO2-Brocker** [ArekKubacki/Hoymiles-Plant-DTU-Pro#32]
Hello,

I have a DTU Pro with the firmware: V00.02.23.
When configuring the RS-485 port, I am asked for a port address. It is possible to choose between 101 and 254. I saw that 502 is preset in the code. I cannot choose this. Can I do this in the config?

**Comment by ArekKubacki** [comment]
RS port - 502
Modbus ID - 101-254
