### ISSUE TITLE
czy jest możliwość dodania  unique_id 

### ISSUE THREAD

**Issue by kmarek1** [ArekKubacki/Hoymiles-Plant-DTU-Pro#5]
Czy jest możliwość dodania  unique_id najbardziej zależy mi nad  'pv_power': [7, 'Aktualna moc']
Co by można był używać sensorów do sterowania

**Comment by ArekKubacki** [comment]
Postaram się dodać jak będę w nim coś grzebał. Osobiście pracuje na Node-Red więc było mi to zbędne.
