### ISSUE TITLE
Problem po aktualizacji HA Core do 2023.2

### ISSUE THREAD

**Issue by januszwoj** [ArekKubacki/Hoymiles-Plant-DTU-Pro#7]
Dzisiaj uaktualniłem HA CORE do wersji 2023.2.
Po restarcie przestały mi działać wszystkie urządzenia podłączone po Modbusie - niestety nie pamiętam już komunikatu błędu.
Mam liczniki i przekaźniki oraz bramkę DTU-PRO.
Wyczytałem w googlu że może to być związane z tym że ta wersja HA CORE korzysta z nowszej wersji pymodbus powyżej 3.0.
Wyłączałem po kolei wszystkie urządzenia/moduły i wyszło, że po wyłączeniu Twojego dodatku cała reszta zaczęła działać.
Teraz jak próbuję odblokować konfigurację w pliku sensor.yaml dostaję taki komunikat błędu w "Developer tools"=>"YAML"=>"CHECK CONFIGURATION"

Configuration invalid!  Platform error sensor.hoymiles_dtu - No module named 'pymodbus.client.sync'

Mam nadzieję, że uda Ci się uaktualnić ten dodatek. Bardzo mi go brakuje.
Janusz
                 
PS. Zastosowałem gniazdko zasilające, które restartuje moją bramkę DTU-PRO codziennie po północy, dzięki temu nie zawiesza mi się i mogę spokojnie ją odpytywać co minutę.

**Comment by ArekKubacki** [comment]
Trwają pracę nad przeniesieniem na nowego pymodbusa. Aktualnie zalecam Downgrade do wersji styczniowej.

**Comment by januszwoj** [comment]
Ok dzięki. Nie mogę się już doczekać nowszej wersji.
