### ISSUE TITLE
Problem z Modbus po aktualizacji

### ISSUE THREAD

**Issue by duma93** [ArekKubacki/Hoymiles-Plant-DTU-Pro#9]
Cześć. 

Korzystam z Integracji do DTU od jakiegoś czasu działa bardzo dobrze natomiast po ostatniej aktualizacji zauważyłem problem z ModBusem. 

Mam połączone dwa liczniki SDM630 i korzystam z integracji na podstawie : https://community.home-assistant.io/t/energy-metering-with-eastron-sdm630-v2-modbus/251737/23

Zauważyłem, że jeśli usunę z pliku /config/configuration.yaml :

modbus:
  - name: waveshare1
    type: rtuovertcp
    host: 192.168.x.xxx
    port: 8888
    sensors: modbus_sensor.yaml

To sprawdzenie konfiguracji przechodzi pozytywnie. Inaczej wyskakuje błąd : 'str' object has no attribute 'get' 

Macie może jakieś rozwiązanie ? 

Pozdr.

**Comment by ArekKubacki** [comment]
Problem nie jest bezpośrednio związany z tematem mojego addonu ale zapewne chodzi o najnowszą bibliotekę pymodbus, którą wymusili twórcy HA.
